name: build-publish

on:
  push:
    tags:
      - 'v*'             # läuft bei Tag-Push z.B. v0.1.21
  release:
    types: [published]   # läuft wenn du im UI auf "Publish release" klickst
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      - run: npm run build
      - run: npm pack
      - run: npm ci

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload TGZ artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-tgz
          path: "*.tgz"
